Update rpc_info

diff --git a/root/aria2/script/rpc_info b/root/aria2/script/rpc_info
--- a/root/aria2/script/rpc_info
+++ b/root/aria2/script/rpc_info
@@ -9,17 +9,28 @@ RPC_TASK_INFO() {
     curl "${RPC_ADDRESS}" -fsSd "${RPC_PAYLOAD}" || curl "https://${RPC_ADDRESS}" -kfsSd "${RPC_PAYLOAD}"
 }
 
-GET_TASK_INFO() {
+GET_RPC_RESULT() {
     RPC_ADDRESS="localhost:${PORT}/jsonrpc"
     RPC_RESULT="$(RPC_TASK_INFO)"
 }
 
 # ======================================================================
 
+GET_DOWNLOAD_DIR() {
+    [[ -z ${RPC_RESULT} ]] && {
+        echo -e "$(DATE_TIME) ${ERROR} Aria2 RPC interface error!"
+        exit 1
+    }
+    DOWNLOAD_DIR=$(echo "${RPC_RESULT}" | jq -r '.result.dir')
+    [[ -z "${DOWNLOAD_DIR}" || "${DOWNLOAD_DIR}" = "null" ]] && {
+        echo ${RPC_RESULT} | jq '.result'
+        echo -e "$(DATE_TIME) ${ERROR} Failed to get download directory!"
+        exit 1
+    }
+}
+
 GET_TASK_STATUS() {
-    GET_TASK_INFO
-    TASK_STATUS=$(cat "${RPC_RESULT}" | jq -r '.result.status')
-    echo "TASK_STATUS=${TASK_STATUS}"
+    TASK_STATUS=$(echo "${RPC_RESULT}" | jq -r '.result.status')
     [[ -z "${TASK_STATUS}" || "${TASK_STATUS}" = "null" ]] && {
         echo "${RPC_RESULT}" | jq '.result'
         echo -e "$(DATE_TIME) ${ERROR} Failed to get task status!"
@@ -28,7 +39,7 @@ GET_TASK_STATUS() {
 }
 
 GET_INFO_HASH() {
-    INFO_HASH=$(cat "${RPC_RESULT}" | jq -r '.result.infoHash')
+    INFO_HASH=$(echo "${RPC_RESULT}" | jq -r '.result.infoHash')
     if [[ -z "${INFO_HASH}" ]]; then
         echo "${RPC_RESULT}" | jq '.result'
         echo -e "$(DATE_TIME) ${ERROR} Failed to get Info Hash!"
@@ -36,6 +47,7 @@ GET_INFO_HASH() {
     elif [[ "${INFO_HASH}" = "null" ]]; then
         return 1
     else
-        TORRENT_FILE="${SOURCE_PATH}/${INFO_HASH}.torrent"
+        TORRENT_FILE="${DOWNLOAD_DIR}/${INFO_HASH}.torrent"
     fi
 }
+
